# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Beta.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'Beta.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nBeta.proto\"u\n\x0e\x44ynamicDuoData\x12\x13\n\x0bpartner_uid\x18\x01 \x01(\x03\x12\r\n\x05score\x18\x03 \x01(\x05\x12\x1a\n\x12\x63reation_timestamp\x18\x04 \x01(\x03\x12\x13\n\x0b\x64\x61ys_active\x18\x05 \x01(\x05\x12\x0e\n\x06status\x18\x06 \x01(\x05\":\n\x15SpecialFriendResponse\x12!\n\x08\x64uo_info\x18\x01 \x01(\x0b\x32\x0f.DynamicDuoDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Beta_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DYNAMICDUODATA']._serialized_start=14
  _globals['_DYNAMICDUODATA']._serialized_end=131
  _globals['_SPECIALFRIENDRESPONSE']._serialized_start=133
  _globals['_SPECIALFRIENDRESPONSE']._serialized_end=191
# @@protoc_insertion_point(module_scope)
